"""FinGuard Module 4 - REST API.

Serves the Module 2 classifier and the Module 3 explanation layer over HTTP so the
React dashboard can score a transaction and show *why* it was scored that way.

    python main.py          # http://localhost:8080, docs at /docs

Three design decisions worth knowing before you read the code:

**The model is loaded once, at startup, not per request.** A 400-tree Random Forest
plus a SHAP TreeExplainer costs seconds to construct and single-digit milliseconds to
run. Building either inside the request handler would turn a 40 ms endpoint into a
4-second one.

**The API keeps a short per-sender history, and it has to.** Four of the model's
features are backward-looking: the gap since the sender's last payment, the size of
that payment, the ratio between them, and whether it went to the same receiver. Those
exist because the "Rs.1 test" scam is invisible in a single row - it is a Rs.1 probe
followed within seconds by a large transfer to the *same* receiver. Score one row in
isolation and `engineer_features` sees no predecessor, so it fills `prev_amount = 0`
and `prev_amount_ratio = amount`, which reads to the model as an enormous jump in
spending and pushes almost anything above the threshold. The history store is what
makes the two-request demo work: POST Rs.1, then POST Rs.50,000 to the same receiver,
and the second call is flagged for the sequence rather than the size. In production
this store is a Redis or feature-store lookup; here it is an in-memory dict with a
TTL, which is honest about being single-process.

**Explanations come from Module 3, not from a reimplementation.** The endpoint calls
`explain_transaction` directly, so the JSON the dashboard renders and the audit report
on disk are generated by the same code path. SHAP values are aggregated by *concept*
before they leave the process, which is why the dashboard receives "age of the
receiving UPI ID" once rather than four correlated columns splitting credit between
them.

**The decision is merchant-side and has three outcomes, not two.** The model returns a
probability; `merchant_policy` turns it into ACCEPT, STEP_UP or HOLD by comparing the
expected rupee cost of each action under the merchant's own economics. A gateway can
challenge a payment with 3-D Secure - an option a bank protecting a consumer does not
have - and a two-outcome API cannot express it. `status` is still emitted as
BLOCKED/APPROVED so existing callers keep working.
"""

from __future__ import annotations

import logging
import os
import re
import threading
import time
import uuid
from collections import deque
from contextlib import asynccontextmanager
from datetime import datetime, timedelta
from pathlib import Path
from typing import Annotated, Any

import pandas as pd
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field, field_validator

from audit_store import VALID_OUTCOMES, store as audit
from chargeback_agent import available_provider, respond_to_dispute
from degradation import Rung, fallback_verdict
from merchant_policy import DEFAULT as MERCHANT, merchant_advice
from explain_model import (
    build_explainer,
    explain_transaction,
    load_model_and_config,
)
from train_model import engineer_features

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
BASE_DIR = Path(__file__).resolve().parent

# Configurable, because 8080 is a popular port and a hardcoded one turns "something
# else is already listening" into a stack trace at startup. FINGUARD_PORT=0 asks the
# OS for a free port, which is what the tests use.
HOST = os.environ.get("FINGUARD_HOST", "0.0.0.0")
PORT = int(os.environ.get("FINGUARD_PORT", "8080"))

# The Vite dev server. Both spellings of the host are listed because a browser sends
# whichever one is in the address bar, and `localhost` and `127.0.0.1` are different
# origins as far as CORS is concerned.
#
# The extra ports are not padding: when 5173 is occupied Vite silently moves to 5174,
# then 5175. Without them listed, that fallback turns into a CORS failure that looks
# like a broken backend rather than a changed port.
ALLOWED_ORIGINS = [
    f"http://{host}:{port}"
    for host in ("localhost", "127.0.0.1")
    for port in (5173, 5174, 5175)
]

# Per-sender history retained for the backward-looking features. Two entries is
# enough - `engineer_features` only shifts by one - but keeping a few makes the
# behaviour easier to inspect. Entries older than the TTL are treated as "no
# recent activity", which is what `time_since_last_txn_sec` is meant to express.
HISTORY_DEPTH = 5
HISTORY_TTL = timedelta(hours=24)
HISTORY_MAX_SENDERS = 10_000

# Applied when the frontend form omits a field the model needs. Account age is the
# one that matters: it is the single strongest feature, and the API cannot invent
# it. Defaulting to an established account is the conservative choice - it biases
# towards approving, so a missing field never manufactures a fraud alert.
DEFAULT_RECEIVER_VPA_AGE_DAYS = 365
DEFAULT_SENDER_CITY = "Mumbai"

# Merchant context the caller may not know. "unknown" is deliberate rather than a
# guess at the commonest category: the encoder was fitted with
# handle_unknown="infrequent_if_exist", so an unseen value lands in the infrequent
# bucket and contributes nothing, whereas defaulting to "grocery" would quietly assert
# a low-risk category for every payment that omitted one.
DEFAULT_MERCHANT_CATEGORY = "unknown"
DEFAULT_PAYMENT_METHOD = "upi"

VPA_PATTERN = re.compile(r"^[A-Za-z0-9._-]{2,64}@[A-Za-z][A-Za-z0-9.-]{1,31}$")

# Lets an operator disable the model at runtime to watch the ladder work. Off unless
# explicitly enabled, because an unauthenticated endpoint that turns off fraud
# detection is exactly the kind of thing that should not exist by default.
CHAOS_ENABLED = os.environ.get("FINGUARD_ENABLE_CHAOS", "").lower() in ("1", "true", "yes")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("finguard.api")


# --------------------------------------------------------------------------- #
# Request / response schemas
# --------------------------------------------------------------------------- #
class TransactionRequest(BaseModel):
    """One UPI transaction to score.

    Only the three form fields are required. Everything below them is optional
    context: supply it if the caller knows it, and the API falls back to its own
    history store or to a documented default if not.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "sender_vpa": "9876543210@ybl",
                "receiver_vpa": "quickcash.help@paytm",
                "amount": 48500.0,
                "receiver_vpa_age_days": 0,
            }
        }
    )

    sender_vpa: str = Field(..., description="Payer VPA, e.g. rahul.verma@okicici")
    receiver_vpa: str = Field(..., description="Payee VPA, e.g. merchant@paytm")
    amount: float = Field(..., gt=0, le=1_000_000, description="Transaction amount in INR")

    receiver_vpa_age_days: int | None = Field(
        None, ge=0, le=1000,
        description=(f"Age of the payee VPA in days. Strongest single feature in the "
                     f"model; defaults to {DEFAULT_RECEIVER_VPA_AGE_DAYS} (an established "
                     f"account) when the caller cannot supply it."),
    )
    timestamp: datetime | None = Field(
        None, description="Transaction time. Defaults to now - the hour matters, because "
                          "the odd-hour phishing signature keys on 01:00-04:00.",
    )
    sender_city: str | None = Field(None, max_length=64, description="Payer's city.")
    time_since_last_txn_sec: float | None = Field(
        None, ge=-1,
        description="Seconds since the sender's previous payment. Derived from the "
                    "server-side history when omitted; -1 means no prior activity.",
    )
    transaction_id: str | None = Field(
        None, max_length=64, description="Client-supplied id. Generated when omitted.",
    )
    merchant_category: str | None = Field(
        None, max_length=64,
        description=("Merchant category, e.g. electronics, travel, digital, grocery. "
                     "Chargeback risk varies sharply across them; unknown when omitted."),
    )
    method: str | None = Field(
        None, max_length=32,
        description="Payment method: upi, card, netbanking or wallet. Defaults to upi.",
    )

    @field_validator("sender_vpa", "receiver_vpa")
    @classmethod
    def _valid_vpa(cls, v: str) -> str:
        v = v.strip()
        if not VPA_PATTERN.match(v):
            raise ValueError(
                "must be a valid UPI VPA of the form name@handle "
                "(letters, digits, dot, underscore or hyphen before the @)"
            )
        return v.lower()

    @field_validator("timestamp")
    @classmethod
    def _naive_local(cls, v: datetime | None) -> datetime | None:
        # The model was trained on naive local timestamps and reads hour-of-day off
        # them directly. An offset-aware value from the browser is converted rather
        # than rejected, otherwise a payment sent at 02:00 IST could be scored as
        # 20:30 UTC and quietly lose the odd-hour signal.
        if v is None:
            return None
        return v.astimezone().replace(tzinfo=None) if v.tzinfo else v


class ShapFeature(BaseModel):
    """One concept's signed contribution to the score.

    Positive pushes towards fraud, negative towards legitimate. Values are summed
    across every column encoding the same concept, so they add up to the model's
    output exactly - that additivity is what makes them usable as an audit trail.
    """

    feature: str
    importance: float


class AnalysisResponse(BaseModel):
    transaction_id: str
    action: str = Field(
        ...,
        description=(
            "ACCEPT, STEP_UP or HOLD. The merchant-side decision: fulfil the order, "
            "challenge it with 3-D Secure before capture, or hold it for review. A "
            "gateway has the middle option and a bank does not, which is why a two-"
            "outcome status is not enough on its own."
        ),
    )
    status: str = Field(
        ...,
        description=(
            "BLOCKED or APPROVED, kept so existing callers keep working. STEP_UP and "
            "HOLD both map to BLOCKED; read `action` for the decision that was made."
        ),
    )
    action_costs: dict[str, float] = Field(
        default_factory=dict,
        description=(
            "Expected rupee cost of each action for this payment, under the merchant's "
            "own economics. The chosen action is the cheapest of the three - no "
            "threshold constant is involved."
        ),
    )
    fraud_probability: float
    execution_time_ms: int
    xai_explanation: str
    shap_features: list[ShapFeature]
    rung: str = Field(
        "full model",
        description="Which rung of the degradation ladder produced this verdict. "
                    "Anything other than 'full model' means the primary scorer was "
                    "unavailable and a coarser fallback answered.",
    )
    degraded: bool = Field(
        False,
        description="True when this verdict came from a fallback rather than the model.",
    )
    decision_id: str | None = Field(
        None,
        description=(
            "Ledger id for this scoring event. Replay the full explanation later at "
            "GET /api/v1/decisions/{decision_id}. Null when the ledger is unavailable - "
            "scoring continues regardless."
        ),
    )


class DisputeRequest(BaseModel):
    """A chargeback raised against a payment the engine already scored."""

    decision_id: str = Field(..., max_length=64,
                             description="The ledger id of the scored payment being disputed.")
    dispute_reason: str = Field(
        ..., min_length=3, max_length=500,
        description="What the issuer says the cardholder claimed, in their words.",
    )


class DispositionRequest(BaseModel):
    """A reviewer's conclusion about an alert."""

    outcome: str = Field(..., description=f"One of {', '.join(VALID_OUTCOMES)}")
    reviewer: str | None = Field(None, max_length=64)
    note: str | None = Field(None, max_length=500)

    @field_validator("outcome")
    @classmethod
    def _known_outcome(cls, v: str) -> str:
        if v not in VALID_OUTCOMES:
            raise ValueError(f"must be one of {', '.join(VALID_OUTCOMES)}")
        return v


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    model_name: str | None = None
    threshold: float | None = None
    trained_at: str | None = None
    senders_tracked: int = 0
    audit_ledger: str = Field(
        "unavailable",
        description="ok, degraded (writes failing, scoring unaffected), or unavailable",
    )
    decisions_recorded: int = 0


# --------------------------------------------------------------------------- #
# Per-sender history
# --------------------------------------------------------------------------- #
class SenderHistory:
    """Recent transactions per sender, so the lag features have something to look at.

    Deliberately small and in-process. Swapping this for Redis is the one change
    needed to run more than one worker; the interface is two methods wide to keep
    that swap cheap.
    """

    def __init__(self, depth: int = HISTORY_DEPTH, ttl: timedelta = HISTORY_TTL,
                 max_senders: int = HISTORY_MAX_SENDERS) -> None:
        self._store: dict[str, deque[dict[str, Any]]] = {}
        self._depth = depth
        self._ttl = ttl
        self._max_senders = max_senders
        self._lock = threading.Lock()

    def recent(self, sender_vpa: str, before: datetime) -> list[dict[str, Any]]:
        """Prior transactions for this sender, oldest first, within the TTL."""
        with self._lock:
            entries = list(self._store.get(sender_vpa, ()))
        cutoff = before - self._ttl
        return [e for e in entries if cutoff <= e["timestamp"] <= before]

    def record(self, row: dict[str, Any]) -> None:
        with self._lock:
            bucket = self._store.setdefault(row["sender_vpa"], deque(maxlen=self._depth))
            bucket.append(row)
            # Crude bound on unbounded growth: a real deployment gets eviction from
            # Redis, not from a dict comprehension.
            if len(self._store) > self._max_senders:
                for key in list(self._store)[: len(self._store) - self._max_senders]:
                    self._store.pop(key, None)

    def __len__(self) -> int:
        with self._lock:
            return len(self._store)


# --------------------------------------------------------------------------- #
# Scoring engine
# --------------------------------------------------------------------------- #
class FraudEngine:
    """Holds the loaded pipeline and explainer, and scores one transaction at a time.

    Scoring is serialised behind a lock. scikit-learn and SHAP are not documented as
    thread-safe, FastAPI runs sync handlers in a threadpool, and a single prediction
    takes tens of milliseconds - so a lock costs nothing at dashboard traffic levels
    and removes a whole class of heisenbug. Throughput scales with processes, not
    threads, which is the usual answer for CPU-bound Python anyway.
    """

    def __init__(self) -> None:
        self.pipeline = None
        self.config: dict[str, Any] = {}
        self.explainer = None
        self.names: list[str] = []
        self.threshold: float = 0.5
        self.history = SenderHistory()
        self._lock = threading.Lock()
        # Set by the chaos endpoint to exercise the ladder in a demo. Never set by a
        # failure - a real failure is caught where it happens.
        self.disabled = False
        self.last_rung = Rung.FULL

    @property
    def ready(self) -> bool:
        return self.pipeline is not None and self.explainer is not None

    def load(self) -> None:
        self.pipeline, self.config = load_model_and_config()
        self.threshold = float(self.config["optimal_threshold"])

        # Module 2 trains with n_jobs=-1, which is right for fitting 400 trees over
        # 80,000 rows and badly wrong for scoring one. Joblib's per-call thread pool
        # costs more to set up than the traversal itself: measured on this model,
        # predict_proba on a single row is 156 ms parallel against 24 ms serial,
        # which is the difference between a 164 ms endpoint and a 47 ms one. Only
        # the in-memory copy is changed; the artifact on disk is untouched.
        classifier = self.pipeline.named_steps.get("classifier")
        if hasattr(classifier, "n_jobs"):
            classifier.n_jobs = 1

        # TreeExplainer with `tree_path_dependent` reads the split statistics baked
        # into the trees, so it needs no background distribution - a single row is
        # enough to hand `build_explainer` the column names it derives from the
        # fitted preprocessor.
        seed = self._to_frame(
            TransactionRequest(sender_vpa="seed.user@okicici", receiver_vpa="seed.shop@paytm",
                               amount=100.0),
            history=[],
        )
        self.explainer, _, self.names = build_explainer(self.pipeline, engineer_features(seed))

        log.info("Loaded %s (trained %s), threshold %.4f [%s policy]",
                 self.config["best_model"], self.config["created_at"], self.threshold,
                 self.config["threshold_policy"]["active_policy"])

    def warm_up(self) -> None:
        """Score one throwaway transaction so the first real request is not the slow one.

        NumPy allocations, SHAP's internal tree arrays and sklearn's validation paths
        all initialise lazily. Without this the first call can take a second or more,
        which on a dashboard looks like the API hanging.
        """
        start = time.perf_counter()
        self.analyze(TransactionRequest(sender_vpa="warmup.user@okicici",
                                        receiver_vpa="warmup.shop@paytm", amount=250.0),
                     remember=False, persist=False)
        log.info("Warm-up prediction completed in %.0f ms", (time.perf_counter() - start) * 1000)

    @staticmethod
    def _to_frame(req: TransactionRequest, history: list[dict[str, Any]]) -> pd.DataFrame:
        """Build the raw frame `engineer_features` expects: history first, then this row.

        Order matters. `engineer_features` derives the lag features with a
        `groupby(sender_vpa).shift(1)`, so the sender's previous transaction has to
        physically precede this one in the frame.
        """
        ts = req.timestamp or datetime.now()
        rows = [
            {
                "timestamp": pd.Timestamp(h["timestamp"]),
                "sender_vpa": h["sender_vpa"],
                "receiver_vpa": h["receiver_vpa"],
                "amount": float(h["amount"]),
                "receiver_vpa_age_days": int(h["receiver_vpa_age_days"]),
                "time_since_last_txn_sec": float(h["time_since_last_txn_sec"]),
                "sender_city": h["sender_city"],
                "merchant_category": h.get("merchant_category", DEFAULT_MERCHANT_CATEGORY),
                "method": h.get("method", DEFAULT_PAYMENT_METHOD),
            }
            for h in history
        ]

        gap = req.time_since_last_txn_sec
        if gap is None:
            gap = (ts - history[-1]["timestamp"]).total_seconds() if history else -1.0

        rows.append({
            "timestamp": pd.Timestamp(ts),
            "sender_vpa": req.sender_vpa,
            "receiver_vpa": req.receiver_vpa,
            "amount": float(req.amount),
            "receiver_vpa_age_days": int(
                req.receiver_vpa_age_days
                if req.receiver_vpa_age_days is not None
                else DEFAULT_RECEIVER_VPA_AGE_DAYS
            ),
            "time_since_last_txn_sec": float(max(gap, -1.0)),
            "sender_city": req.sender_city or DEFAULT_SENDER_CITY,
            "merchant_category": req.merchant_category or DEFAULT_MERCHANT_CATEGORY,
            "method": req.method or DEFAULT_PAYMENT_METHOD,
        })
        return pd.DataFrame(rows)

    def _fallback_response(self, req, ts, raw_frame, current, elapsed_from,
                           remember: bool, persist: bool | None) -> AnalysisResponse:
        """Score on a lower rung and answer honestly about it.

        No SHAP values are invented. A fallback verdict carries the reasons the rule
        engine actually used and an explanation that says the model was unavailable -
        a made-up explanation would be worse than none, because it would flow into the
        ledger and be read months later as though the model had produced it.
        """
        verdict = fallback_verdict(
            amount=float(req.amount),
            receiver_vpa_age_days=req.receiver_vpa_age_days,
            timestamp=ts,
            rules_available=True,
        )
        self.last_rung = verdict.rung

        if remember:
            self.history.record(raw_frame.loc[current].to_dict())

        txn_id = req.transaction_id or f"tx-{uuid.uuid4().hex[:12]}"
        elapsed_ms = int(round((time.perf_counter() - elapsed_from) * 1000))
        log.info("%s  %s -> %s  Rs.%s  %s  [%s]  (%d ms)",
                 txn_id, req.sender_vpa, req.receiver_vpa, f"{req.amount:,.2f}",
                 verdict.action, verdict.rung.name, elapsed_ms)

        decision_id = None
        if (persist if persist is not None else remember) and audit.ready:
            decision_id = audit.record_decision(
                transaction_id=txn_id, sender_vpa=req.sender_vpa,
                receiver_vpa=req.receiver_vpa, amount=float(req.amount),
                receiver_vpa_age_days=req.receiver_vpa_age_days,
                txn_timestamp=ts.isoformat(), sender_city=req.sender_city,
                # -1 is an explicit "no probability was produced", never a score. A
                # zero here would read as "the model was certain it was legitimate".
                fraud_probability=-1.0, threshold=self.threshold,
                decision=verdict.action,
                model_name=f"fallback:{verdict.rung.name}",
                model_trained_at=None, threshold_policy=None,
                latency_ms=elapsed_ms, reasons=list(verdict.reasons),
                shap_concepts={},
            )

        return AnalysisResponse(
            transaction_id=txn_id,
            action=verdict.action,
            status="BLOCKED" if verdict.action != "ACCEPT" else "APPROVED",
            action_costs={},
            fraud_probability=0.0,
            rung=verdict.rung.label,
            degraded=True,
            execution_time_ms=elapsed_ms,
            xai_explanation=verdict.explanation,
            shap_features=[],
            decision_id=decision_id,
        )

    def analyze(self, req: TransactionRequest, remember: bool = True,
                persist: bool | None = None) -> AnalysisResponse:
        start = time.perf_counter()
        ts = req.timestamp or datetime.now()

        history = self.history.recent(req.sender_vpa, before=ts)
        raw_frame = self._to_frame(req, history)
        current = raw_frame.index[-1]

        # Rung 0. Anything that goes wrong below - a corrupt artifact, a SHAP error, a
        # feature the preprocessor has never seen - descends the ladder rather than
        # returning a 500. Payments do not stop arriving because a joblib file did.
        try:
            if self.disabled:
                raise RuntimeError("scoring disabled by operator")
            with self._lock:
                features = engineer_features(raw_frame)
                result = explain_transaction(
                    self.explainer, self.pipeline, self.names,
                    features, raw_frame.loc[current], self.threshold,
                )
        except Exception as exc:                      # noqa: BLE001
            log.error("Full scoring unavailable (%s); descending the ladder.", exc)
            return self._fallback_response(req, ts, raw_frame, current, elapsed_from=start,
                                           remember=remember, persist=persist)

        # The model produces a probability; the merchant's cost structure turns it
        # into an action. `result["decision"]` is still the bank-style block/allow
        # call at the calibrated threshold, kept for the `status` field and for
        # continuity with the training report.
        probability = result["probability"]
        action = MERCHANT.decide(probability, float(req.amount))
        costs = MERCHANT.action_costs(probability, float(req.amount))
        blocked = action != "ACCEPT"
        concepts = result["concepts"]
        # `concepts` arrives sorted by absolute contribution, so the dashboard's
        # first bar is the strongest driver whichever way it points.
        shap_features = [
            ShapFeature(feature=name, importance=round(float(value), 6))
            for name, value in concepts.items()
            if abs(value) > 1e-6
        ]

        if remember:
            self.history.record(raw_frame.loc[current].to_dict())

        txn_id = req.transaction_id or f"tx-{uuid.uuid4().hex[:12]}"
        elapsed_ms = int(round((time.perf_counter() - start) * 1000))
        log.info("%s  %s -> %s  Rs.%s  p=%.4f  %s  (%d ms)",
                 txn_id, req.sender_vpa, req.receiver_vpa, f"{req.amount:,.2f}",
                 probability, action, elapsed_ms)

        # The ledger stores every concept with its signed value, not the filtered list
        # the dashboard renders. A stored top-3 would be a *view* of the explanation
        # rather than the explanation, and could never be re-derived into another one.
        decision_id = None
        if (persist if persist is not None else remember) and audit.ready:
            decision_id = audit.record_decision(
                transaction_id=txn_id,
                sender_vpa=req.sender_vpa,
                receiver_vpa=req.receiver_vpa,
                amount=float(req.amount),
                receiver_vpa_age_days=req.receiver_vpa_age_days,
                txn_timestamp=ts.isoformat(),
                sender_city=req.sender_city,
                fraud_probability=result["probability"],
                threshold=self.threshold,
                decision=action,
                model_name=str(self.config.get("best_model", "unknown")),
                model_trained_at=self.config.get("created_at"),
                threshold_policy=self.config.get("threshold_policy", {}).get("active_policy"),
                latency_ms=elapsed_ms,
                reasons=list(result["reasons"]),
                shap_concepts={str(k): float(v) for k, v in concepts.items()},
            )

        return AnalysisResponse(
            transaction_id=txn_id,
            action=action,
            status="BLOCKED" if blocked else "APPROVED",
            action_costs=costs,
            fraud_probability=round(probability, 4),
            rung=Rung.FULL.label,
            degraded=False,
            execution_time_ms=elapsed_ms,
            xai_explanation=merchant_advice(action, float(req.amount), result["reasons"]),
            shap_features=shap_features,
            decision_id=decision_id,
        )


engine = FraudEngine()


# --------------------------------------------------------------------------- #
# Application
# --------------------------------------------------------------------------- #
@asynccontextmanager
async def lifespan(app: FastAPI):
    # The ledger is opened before the model: if scoring works, every decision it
    # produces must be recordable. A ledger failure is downgraded to a warning rather
    # than a startup abort, for the same reason writes are - bookkeeping must never
    # be the thing that stops a fraud engine from detecting fraud.
    try:
        audit.connect()
    except Exception as exc:                          # noqa: BLE001
        log.error("Audit ledger unavailable, scoring will continue unrecorded: %s", exc)

    log.info("Loading FinGuard artifacts from %s ...", BASE_DIR / "models")
    try:
        engine.load()
        engine.warm_up()
    except FileNotFoundError as exc:
        # Start anyway so /api/v1/health can report the problem, rather than dying
        # with a stack trace the frontend developer has to go read in a terminal.
        log.error("%s", exc)
        log.error("Run `python train_model.py` (Module 2) to produce the artifacts.")
    yield
    audit.close()
    log.info("Shutting down.")


app = FastAPI(
    title="FinGuard API",
    description="Real-time UPI fraud detection with SHAP-based explanations.",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def require_engine() -> FraudEngine:
    if not engine.ready:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Model artifacts are not loaded. Run `python train_model.py` and restart.",
        )
    return engine


@app.exception_handler(Exception)
async def unhandled_error(request: Request, exc: Exception) -> JSONResponse:
    log.exception("Unhandled error on %s", request.url.path)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "Internal scoring error. Check the API logs."},
    )


@app.post("/api/v1/analyze-transaction", response_model=AnalysisResponse,
          summary="Score one UPI transaction and explain the decision")
def analyze_transaction(
    payload: TransactionRequest,
    svc: Annotated[FraudEngine, Depends(require_engine)],
) -> AnalysisResponse:
    """Return a fraud probability, a block/approve decision, and the reasons for it.

    The decision uses the cost-calibrated threshold from Module 2 rather than a naive
    0.5, so a payment can be blocked well below 50% probability - that is deliberate:
    a missed mule transfer costs its full value, a false alarm costs one review.
    """
    return svc.analyze(payload)


def _ledger_state() -> tuple[str, int]:
    """Ledger health and volume, degrading quietly rather than raising.

    A failure here must not turn the health probe itself into an error - the probe
    exists precisely so an operator can see partial failure, and a /health that 500s
    when the ledger is sick reports nothing at all.
    """
    if not audit.ready:
        return "unavailable", 0
    try:
        return ("degraded" if audit.degraded else "ok"), audit.stats()["decisions_recorded"]
    except Exception:                                 # noqa: BLE001
        return "degraded", 0


@app.get("/api/v1/health", response_model=HealthResponse, summary="Liveness and model status")
def health() -> HealthResponse:
    ledger, recorded = _ledger_state()
    if not engine.ready:
        return HealthResponse(status="degraded", model_loaded=False,
                              audit_ledger=ledger, decisions_recorded=recorded)
    return HealthResponse(
        status="ok",
        model_loaded=True,
        model_name=engine.config.get("best_model"),
        threshold=round(engine.threshold, 4),
        trained_at=engine.config.get("created_at"),
        senders_tracked=len(engine.history),
        audit_ledger=ledger,
        decisions_recorded=recorded,
    )


# --------------------------------------------------------------------------- #
# Decision ledger
# --------------------------------------------------------------------------- #
def require_ledger() -> None:
    if not audit.ready:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Decision ledger is unavailable. Scoring still works; history does not.",
        )


@app.get("/api/v1/decisions", summary="Recent scoring decisions, newest first")
def list_decisions(
    limit: int = 50,
    offset: int = 0,
    only_actioned: bool = False,
) -> dict[str, Any]:
    """The alert queue.

    Each entry carries its latest analyst disposition, so a reviewer can see at a
    glance what has already been judged and what is still waiting.
    """
    require_ledger()
    return {"decisions": audit.recent_decisions(limit=limit, offset=offset,
                                                only_actioned=only_actioned)}


@app.get("/api/v1/decisions/{decision_id}", summary="Replay one decision in full")
def get_decision(decision_id: str) -> dict[str, Any]:
    """Everything recorded about one scoring event.

    This is the endpoint that makes the audit trail real: months after the fact, and
    after the model has been retrained, it returns the probability, the threshold and
    policy in force at the time, the model version that produced it, and every SHAP
    concept with its signed contribution.
    """
    require_ledger()
    record = audit.get_decision(decision_id)
    if record is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"No decision {decision_id!r} in the ledger.")
    return record


@app.post("/api/v1/decisions/{decision_id}/disposition",
          status_code=status.HTTP_201_CREATED,
          summary="Record a reviewer's conclusion about an alert")
def add_disposition(decision_id: str, payload: DispositionRequest) -> dict[str, Any]:
    """Attach a human outcome to a decision.

    Written as a new row rather than an update: the model's decision stays immutable,
    and a reviewer who changes their mind adds another judgement instead of erasing
    the first. These rows are what `GET /api/v1/stats` computes reviewed precision from.
    """
    require_ledger()
    try:
        return audit.record_disposition(decision_id, payload.outcome,
                                        payload.reviewer, payload.note)
    except KeyError:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"No decision {decision_id!r} in the ledger.") from None


@app.post("/api/v1/disputes", status_code=status.HTTP_201_CREATED,
          summary="Draft a representment packet for a disputed payment")
def raise_dispute(payload: DisputeRequest) -> dict[str, Any]:
    """Reconstruct the case from the ledger and draft the dispute response.

    The only endpoint in FinGuard that calls a language model, and it sits deliberately
    outside the decision path: the score was made by the Random Forest months ago and
    is not revisited here. The model assembles evidence into a document.

    It never fails for want of a model. No credentials, a timeout, a refusal, a
    response that does not validate - each falls back to a deterministic draft built
    from the same evidence, flagged `degraded: true`. A dispute has a filing deadline,
    and returning nothing because a third-party API was unreachable is the worse
    outcome by a wide margin.
    """
    require_ledger()
    try:
        result = respond_to_dispute(payload.decision_id, payload.dispute_reason, store=audit)
    except KeyError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No decision {payload.decision_id!r} in the ledger to dispute.",
        ) from None

    stored = audit.record_dispute(payload.decision_id, payload.dispute_reason, result["packet"])
    log.info("%s  dispute on %s -> %s (confidence %.2f, drafted by %s)",
             stored["dispute_id"], payload.decision_id,
             result["packet"]["recommendation"], result["packet"]["confidence"],
             result["packet"]["generated_by"])

    return {**stored, **result}


@app.get("/api/v1/disputes/{dispute_id}", summary="Retrieve a drafted representment packet")
def get_dispute(dispute_id: str) -> dict[str, Any]:
    require_ledger()
    record = audit.get_dispute(dispute_id)
    if record is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"No dispute {dispute_id!r} in the ledger.")
    return record


@app.get("/api/v1/stats", summary="Live operating summary")
def stats() -> dict[str, Any]:
    """Volume, block rate, rupees held, and precision over reviewed alerts only.

    Precision is reported against analyst dispositions rather than the training
    labels, because in production there are no labels - only outcomes a human
    eventually confirms. Alerts nobody has reviewed are excluded rather than assumed
    correct, which is why this number can differ from the one in the evaluation report.
    """
    require_ledger()
    return audit.stats()


@app.get("/api/v1/health/deep", summary="Per-dependency status and the active rung")
def health_deep() -> dict[str, Any]:
    """Every dependency, and which rung the engine would answer on right now.

    The shallow probe answers "is it up". This answers "what is it currently able to
    do", which is the question that matters during a partial outage - and it is the
    difference between noticing a silent fallback and discovering it in a monthly
    report when the alert rate has moved.
    """
    ledger_state, recorded = _ledger_state()
    provider = available_provider()

    rung = Rung.FULL if (engine.ready and not engine.disabled) else Rung.RULES
    return {
        "rung": int(rung),
        "rung_label": rung.label,
        "serving": rung == Rung.FULL,
        "dependencies": {
            "model": {
                "status": "ok" if engine.ready and not engine.disabled else "unavailable",
                "name": engine.config.get("best_model") if engine.ready else None,
                "trained_at": engine.config.get("created_at") if engine.ready else None,
                "disabled_by_operator": engine.disabled,
            },
            "explainer": {"status": "ok" if engine.explainer is not None else "unavailable"},
            "rule_engine": {"status": "ok", "note": "always available - pure function, no artifacts"},
            "audit_ledger": {"status": ledger_state, "decisions_recorded": recorded,
                             "last_error": audit.last_error},
            "llm_provider": {
                "status": "configured" if provider else "absent",
                "provider": provider[0] if provider else None,
                "note": "absent means dispute packets are drafted from templates",
            },
        },
        "chaos_endpoint_enabled": CHAOS_ENABLED,
    }


@app.post("/api/v1/admin/chaos/model", include_in_schema=False,
          summary="Disable or restore the model, to exercise the ladder")
def chaos_model(disable: bool = True) -> dict[str, Any]:
    """Turn the primary scorer off and watch the fallback take over.

    Disabled unless FINGUARD_ENABLE_CHAOS is set. An unauthenticated endpoint that
    switches off fraud detection is not something that should exist by default, and
    the whole point of the ladder is that it works without anyone asking it to.
    """
    if not CHAOS_ENABLED:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Chaos endpoint disabled. Set FINGUARD_ENABLE_CHAOS=1 to enable it.",
        )
    engine.disabled = bool(disable)
    log.warning("Model %s by operator via chaos endpoint.",
                "DISABLED" if engine.disabled else "restored")
    return {"model_disabled": engine.disabled,
            "rung": Rung.RULES.label if engine.disabled else Rung.FULL.label}


@app.get("/", include_in_schema=False)
def root() -> dict[str, str]:
    return {"service": "FinGuard API", "docs": "/docs", "health": "/api/v1/health"}


if __name__ == "__main__":
    import socket

    import uvicorn

    def _port_is_free(host: str, port: int) -> bool:
        if port == 0:
            return True
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
            probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            return probe.connect_ex(("127.0.0.1", port)) != 0

    if not _port_is_free(HOST, PORT):
        # Checked before uvicorn binds, so the message names the fix rather than
        # surfacing an OSError from deep inside the server's startup path.
        log.error("Port %d is already in use. Start on another one with "
                  "FINGUARD_PORT=8090 python main.py, and point the dashboard at it "
                  "with VITE_API_BASE_URL=http://localhost:8090.", PORT)
        raise SystemExit(1)

    # reload=False on purpose: the reloader would re-import the module and rebuild
    # the 400-tree explainer on every file save.
    uvicorn.run(app, host=HOST, port=PORT, log_level="info")
