"""FinGuard Module 4 - REST API.

Serves the Module 2 classifier and the Module 3 explanation layer over HTTP so the
React dashboard can score a transaction and show *why* it was scored that way.

    python main.py          # http://localhost:8080, docs at /docs

Three design decisions worth knowing before you read the code:

**The model is loaded once, at startup, not per request.** A 400-tree Random Forest
plus a SHAP TreeExplainer costs seconds to construct and single-digit milliseconds to
run. Building either inside the request handler would turn a 40 ms endpoint into a
4-second one.

**The API keeps a short per-sender history, and it has to.** Four of the model's
features are backward-looking: the gap since the sender's last payment, the size of
that payment, the ratio between them, and whether it went to the same receiver. Those
exist because the "Rs.1 test" scam is invisible in a single row - it is a Rs.1 probe
followed within seconds by a large transfer to the *same* receiver. Score one row in
isolation and `engineer_features` sees no predecessor, so it fills `prev_amount = 0`
and `prev_amount_ratio = amount`, which reads to the model as an enormous jump in
spending and pushes almost anything above the threshold. The history store is what
makes the two-request demo work: POST Rs.1, then POST Rs.50,000 to the same receiver,
and the second call is flagged for the sequence rather than the size. In production
this store is a Redis or feature-store lookup; here it is an in-memory dict with a
TTL, which is honest about being single-process.

**Explanations come from Module 3, not from a reimplementation.** The endpoint calls
`explain_transaction` and `customer_notification` directly, so the JSON the dashboard
renders and the audit report on disk are generated by the same code path. SHAP values
are aggregated by *concept* before they leave the process, which is why the dashboard
receives "age of the receiving UPI ID" once rather than four correlated columns
splitting credit between them.
"""

from __future__ import annotations

import logging
import re
import threading
import time
import uuid
from collections import deque
from contextlib import asynccontextmanager
from datetime import datetime, timedelta
from pathlib import Path
from typing import Annotated, Any

import pandas as pd
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field, field_validator

from explain_model import (
    build_explainer,
    customer_notification,
    explain_transaction,
    load_model_and_config,
)
from train_model import engineer_features

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
BASE_DIR = Path(__file__).resolve().parent

HOST = "0.0.0.0"
PORT = 8080

# The Vite dev server. Both spellings of the host are listed because a browser sends
# whichever one is in the address bar, and `localhost` and `127.0.0.1` are different
# origins as far as CORS is concerned.
#
# The extra ports are not padding: when 5173 is occupied Vite silently moves to 5174,
# then 5175. Without them listed, that fallback turns into a CORS failure that looks
# like a broken backend rather than a changed port.
ALLOWED_ORIGINS = [
    f"http://{host}:{port}"
    for host in ("localhost", "127.0.0.1")
    for port in (5173, 5174, 5175)
]

# Per-sender history retained for the backward-looking features. Two entries is
# enough - `engineer_features` only shifts by one - but keeping a few makes the
# behaviour easier to inspect. Entries older than the TTL are treated as "no
# recent activity", which is what `time_since_last_txn_sec` is meant to express.
HISTORY_DEPTH = 5
HISTORY_TTL = timedelta(hours=24)
HISTORY_MAX_SENDERS = 10_000

# Applied when the frontend form omits a field the model needs. Account age is the
# one that matters: it is the single strongest feature, and the API cannot invent
# it. Defaulting to an established account is the conservative choice - it biases
# towards approving, so a missing field never manufactures a fraud alert.
DEFAULT_RECEIVER_VPA_AGE_DAYS = 365
DEFAULT_SENDER_CITY = "Mumbai"

VPA_PATTERN = re.compile(r"^[A-Za-z0-9._-]{2,64}@[A-Za-z][A-Za-z0-9.-]{1,31}$")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("finguard.api")


# --------------------------------------------------------------------------- #
# Request / response schemas
# --------------------------------------------------------------------------- #
class TransactionRequest(BaseModel):
    """One UPI transaction to score.

    Only the three form fields are required. Everything below them is optional
    context: supply it if the caller knows it, and the API falls back to its own
    history store or to a documented default if not.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "sender_vpa": "9876543210@ybl",
                "receiver_vpa": "quickcash.help@paytm",
                "amount": 48500.0,
                "receiver_vpa_age_days": 0,
            }
        }
    )

    sender_vpa: str = Field(..., description="Payer VPA, e.g. rahul.verma@okicici")
    receiver_vpa: str = Field(..., description="Payee VPA, e.g. merchant@paytm")
    amount: float = Field(..., gt=0, le=1_000_000, description="Transaction amount in INR")

    receiver_vpa_age_days: int | None = Field(
        None, ge=0, le=1000,
        description=(f"Age of the payee VPA in days. Strongest single feature in the "
                     f"model; defaults to {DEFAULT_RECEIVER_VPA_AGE_DAYS} (an established "
                     f"account) when the caller cannot supply it."),
    )
    timestamp: datetime | None = Field(
        None, description="Transaction time. Defaults to now - the hour matters, because "
                          "the odd-hour phishing signature keys on 01:00-04:00.",
    )
    sender_city: str | None = Field(None, max_length=64, description="Payer's city.")
    time_since_last_txn_sec: float | None = Field(
        None, ge=-1,
        description="Seconds since the sender's previous payment. Derived from the "
                    "server-side history when omitted; -1 means no prior activity.",
    )
    transaction_id: str | None = Field(
        None, max_length=64, description="Client-supplied id. Generated when omitted.",
    )

    @field_validator("sender_vpa", "receiver_vpa")
    @classmethod
    def _valid_vpa(cls, v: str) -> str:
        v = v.strip()
        if not VPA_PATTERN.match(v):
            raise ValueError(
                "must be a valid UPI VPA of the form name@handle "
                "(letters, digits, dot, underscore or hyphen before the @)"
            )
        return v.lower()

    @field_validator("timestamp")
    @classmethod
    def _naive_local(cls, v: datetime | None) -> datetime | None:
        # The model was trained on naive local timestamps and reads hour-of-day off
        # them directly. An offset-aware value from the browser is converted rather
        # than rejected, otherwise a payment sent at 02:00 IST could be scored as
        # 20:30 UTC and quietly lose the odd-hour signal.
        if v is None:
            return None
        return v.astimezone().replace(tzinfo=None) if v.tzinfo else v


class ShapFeature(BaseModel):
    """One concept's signed contribution to the score.

    Positive pushes towards fraud, negative towards legitimate. Values are summed
    across every column encoding the same concept, so they add up to the model's
    output exactly - that additivity is what makes them usable as an audit trail.
    """

    feature: str
    importance: float


class AnalysisResponse(BaseModel):
    transaction_id: str
    status: str = Field(..., description="BLOCKED or APPROVED")
    fraud_probability: float
    execution_time_ms: int
    xai_explanation: str
    shap_features: list[ShapFeature]


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    model_name: str | None = None
    threshold: float | None = None
    trained_at: str | None = None
    senders_tracked: int = 0


# --------------------------------------------------------------------------- #
# Per-sender history
# --------------------------------------------------------------------------- #
class SenderHistory:
    """Recent transactions per sender, so the lag features have something to look at.

    Deliberately small and in-process. Swapping this for Redis is the one change
    needed to run more than one worker; the interface is two methods wide to keep
    that swap cheap.
    """

    def __init__(self, depth: int = HISTORY_DEPTH, ttl: timedelta = HISTORY_TTL,
                 max_senders: int = HISTORY_MAX_SENDERS) -> None:
        self._store: dict[str, deque[dict[str, Any]]] = {}
        self._depth = depth
        self._ttl = ttl
        self._max_senders = max_senders
        self._lock = threading.Lock()

    def recent(self, sender_vpa: str, before: datetime) -> list[dict[str, Any]]:
        """Prior transactions for this sender, oldest first, within the TTL."""
        with self._lock:
            entries = list(self._store.get(sender_vpa, ()))
        cutoff = before - self._ttl
        return [e for e in entries if cutoff <= e["timestamp"] <= before]

    def record(self, row: dict[str, Any]) -> None:
        with self._lock:
            bucket = self._store.setdefault(row["sender_vpa"], deque(maxlen=self._depth))
            bucket.append(row)
            # Crude bound on unbounded growth: a real deployment gets eviction from
            # Redis, not from a dict comprehension.
            if len(self._store) > self._max_senders:
                for key in list(self._store)[: len(self._store) - self._max_senders]:
                    self._store.pop(key, None)

    def __len__(self) -> int:
        with self._lock:
            return len(self._store)


# --------------------------------------------------------------------------- #
# Scoring engine
# --------------------------------------------------------------------------- #
class FraudEngine:
    """Holds the loaded pipeline and explainer, and scores one transaction at a time.

    Scoring is serialised behind a lock. scikit-learn and SHAP are not documented as
    thread-safe, FastAPI runs sync handlers in a threadpool, and a single prediction
    takes tens of milliseconds - so a lock costs nothing at dashboard traffic levels
    and removes a whole class of heisenbug. Throughput scales with processes, not
    threads, which is the usual answer for CPU-bound Python anyway.
    """

    def __init__(self) -> None:
        self.pipeline = None
        self.config: dict[str, Any] = {}
        self.explainer = None
        self.names: list[str] = []
        self.threshold: float = 0.5
        self.history = SenderHistory()
        self._lock = threading.Lock()

    @property
    def ready(self) -> bool:
        return self.pipeline is not None and self.explainer is not None

    def load(self) -> None:
        self.pipeline, self.config = load_model_and_config()
        self.threshold = float(self.config["optimal_threshold"])

        # Module 2 trains with n_jobs=-1, which is right for fitting 400 trees over
        # 80,000 rows and badly wrong for scoring one. Joblib's per-call thread pool
        # costs more to set up than the traversal itself: measured on this model,
        # predict_proba on a single row is 156 ms parallel against 24 ms serial,
        # which is the difference between a 164 ms endpoint and a 47 ms one. Only
        # the in-memory copy is changed; the artifact on disk is untouched.
        classifier = self.pipeline.named_steps.get("classifier")
        if hasattr(classifier, "n_jobs"):
            classifier.n_jobs = 1

        # TreeExplainer with `tree_path_dependent` reads the split statistics baked
        # into the trees, so it needs no background distribution - a single row is
        # enough to hand `build_explainer` the column names it derives from the
        # fitted preprocessor.
        seed = self._to_frame(
            TransactionRequest(sender_vpa="seed.user@okicici", receiver_vpa="seed.shop@paytm",
                               amount=100.0),
            history=[],
        )
        self.explainer, _, self.names = build_explainer(self.pipeline, engineer_features(seed))

        log.info("Loaded %s (trained %s), threshold %.4f [%s policy]",
                 self.config["best_model"], self.config["created_at"], self.threshold,
                 self.config["threshold_policy"]["active_policy"])

    def warm_up(self) -> None:
        """Score one throwaway transaction so the first real request is not the slow one.

        NumPy allocations, SHAP's internal tree arrays and sklearn's validation paths
        all initialise lazily. Without this the first call can take a second or more,
        which on a dashboard looks like the API hanging.
        """
        start = time.perf_counter()
        self.analyze(TransactionRequest(sender_vpa="warmup.user@okicici",
                                        receiver_vpa="warmup.shop@paytm", amount=250.0),
                     remember=False)
        log.info("Warm-up prediction completed in %.0f ms", (time.perf_counter() - start) * 1000)

    @staticmethod
    def _to_frame(req: TransactionRequest, history: list[dict[str, Any]]) -> pd.DataFrame:
        """Build the raw frame `engineer_features` expects: history first, then this row.

        Order matters. `engineer_features` derives the lag features with a
        `groupby(sender_vpa).shift(1)`, so the sender's previous transaction has to
        physically precede this one in the frame.
        """
        ts = req.timestamp or datetime.now()
        rows = [
            {
                "timestamp": pd.Timestamp(h["timestamp"]),
                "sender_vpa": h["sender_vpa"],
                "receiver_vpa": h["receiver_vpa"],
                "amount": float(h["amount"]),
                "receiver_vpa_age_days": int(h["receiver_vpa_age_days"]),
                "time_since_last_txn_sec": float(h["time_since_last_txn_sec"]),
                "sender_city": h["sender_city"],
            }
            for h in history
        ]

        gap = req.time_since_last_txn_sec
        if gap is None:
            gap = (ts - history[-1]["timestamp"]).total_seconds() if history else -1.0

        rows.append({
            "timestamp": pd.Timestamp(ts),
            "sender_vpa": req.sender_vpa,
            "receiver_vpa": req.receiver_vpa,
            "amount": float(req.amount),
            "receiver_vpa_age_days": int(
                req.receiver_vpa_age_days
                if req.receiver_vpa_age_days is not None
                else DEFAULT_RECEIVER_VPA_AGE_DAYS
            ),
            "time_since_last_txn_sec": float(max(gap, -1.0)),
            "sender_city": req.sender_city or DEFAULT_SENDER_CITY,
        })
        return pd.DataFrame(rows)

    def analyze(self, req: TransactionRequest, remember: bool = True) -> AnalysisResponse:
        start = time.perf_counter()
        ts = req.timestamp or datetime.now()

        history = self.history.recent(req.sender_vpa, before=ts)
        raw_frame = self._to_frame(req, history)
        current = raw_frame.index[-1]

        with self._lock:
            features = engineer_features(raw_frame)
            result = explain_transaction(
                self.explainer, self.pipeline, self.names,
                features, raw_frame.loc[current], self.threshold,
            )

        blocked = result["decision"] == "BLOCK"
        concepts = result["concepts"]
        # `concepts` arrives sorted by absolute contribution, so the dashboard's
        # first bar is the strongest driver whichever way it points.
        shap_features = [
            ShapFeature(feature=name, importance=round(float(value), 6))
            for name, value in concepts.items()
            if abs(value) > 1e-6
        ]

        if remember:
            self.history.record(raw_frame.loc[current].to_dict())

        txn_id = req.transaction_id or f"tx-{uuid.uuid4().hex[:12]}"
        elapsed_ms = int(round((time.perf_counter() - start) * 1000))
        log.info("%s  %s -> %s  Rs.%s  p=%.4f  %s  (%d ms)",
                 txn_id, req.sender_vpa, req.receiver_vpa, f"{req.amount:,.2f}",
                 result["probability"], "BLOCKED" if blocked else "APPROVED", elapsed_ms)

        return AnalysisResponse(
            transaction_id=txn_id,
            status="BLOCKED" if blocked else "APPROVED",
            fraud_probability=round(result["probability"], 4),
            execution_time_ms=elapsed_ms,
            xai_explanation=customer_notification(req.amount, result["reasons"], blocked),
            shap_features=shap_features,
        )


engine = FraudEngine()


# --------------------------------------------------------------------------- #
# Application
# --------------------------------------------------------------------------- #
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("Loading FinGuard artifacts from %s ...", BASE_DIR / "models")
    try:
        engine.load()
        engine.warm_up()
    except FileNotFoundError as exc:
        # Start anyway so /api/v1/health can report the problem, rather than dying
        # with a stack trace the frontend developer has to go read in a terminal.
        log.error("%s", exc)
        log.error("Run `python train_model.py` (Module 2) to produce the artifacts.")
    yield
    log.info("Shutting down.")


app = FastAPI(
    title="FinGuard API",
    description="Real-time UPI fraud detection with SHAP-based explanations.",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def require_engine() -> FraudEngine:
    if not engine.ready:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Model artifacts are not loaded. Run `python train_model.py` and restart.",
        )
    return engine


@app.exception_handler(Exception)
async def unhandled_error(request: Request, exc: Exception) -> JSONResponse:
    log.exception("Unhandled error on %s", request.url.path)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "Internal scoring error. Check the API logs."},
    )


@app.post("/api/v1/analyze-transaction", response_model=AnalysisResponse,
          summary="Score one UPI transaction and explain the decision")
def analyze_transaction(
    payload: TransactionRequest,
    svc: Annotated[FraudEngine, Depends(require_engine)],
) -> AnalysisResponse:
    """Return a fraud probability, a block/approve decision, and the reasons for it.

    The decision uses the cost-calibrated threshold from Module 2 rather than a naive
    0.5, so a payment can be blocked well below 50% probability - that is deliberate:
    a missed mule transfer costs its full value, a false alarm costs one review.
    """
    return svc.analyze(payload)


@app.get("/api/v1/health", response_model=HealthResponse, summary="Liveness and model status")
def health() -> HealthResponse:
    if not engine.ready:
        return HealthResponse(status="degraded", model_loaded=False)
    return HealthResponse(
        status="ok",
        model_loaded=True,
        model_name=engine.config.get("best_model"),
        threshold=round(engine.threshold, 4),
        trained_at=engine.config.get("created_at"),
        senders_tracked=len(engine.history),
    )


@app.get("/", include_in_schema=False)
def root() -> dict[str, str]:
    return {"service": "FinGuard API", "docs": "/docs", "health": "/api/v1/health"}


if __name__ == "__main__":
    import uvicorn

    # reload=False on purpose: the reloader would re-import the module and rebuild
    # the 400-tree explainer on every file save.
    uvicorn.run(app, host=HOST, port=PORT, log_level="info")
